version: "23.0.5"
services:
  discovery:
    build: ./eurekaserver
    ports:
    - 8761:8761
    image: eureka_image

  candidat:
    build: ./projetmicroservicecontrat
    environment:
    - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    ports:
    - 9000:9000
    image: candidate-service
    depends_on:
    - discovery
